### ISSUE TITLE
Automatically deploy Docker Image to IBM cloud

### ISSUE THREAD

**Issue by christophernixon** [christophernixon/DevOps-Pipeline-sweng#38]
This issue is dependent on Issue #37 and Issue #39 being complete. Having successfully built our docker image and tagged it using Travis CI, we need to push it to our Container Registry in IBM cloud. 

This is done via a bash script.

Adding the following to the .travis.yml file will:
1) Assign executable permissions to any script contained in the ./scripts folder.
2) Execute a bash script and pass in the container registry namespace and cluster namespace as parameters.
```
deploy:
  - provider: script
    skip_cleanup: true
    # script: chmod +x ./scripts/* && ./scripts/execute.sh <Cluster Namespace> <Container Registry Namespace>
    script: chmod +x ./scripts/* && ./scripts/execute.sh demo-namespace-prod demo-production
    on:
      branch: master
```

Now that we have Travis Ci executing a script to deploy our docker image, the script itself needs to be written.  This script can be heavily based on [this script](https://github.com/pawanpinjarkar/Build-Node-JS-Docker-images-and-push-to-Kubernetes-via-Travis-CI-on-IBM-Cloud/blob/master/scripts/execute.sh) from a GitHub repo for pushing docker images to Kubernetes on IBM cloud. 

Note that this script only deploys our __Docker Image__ to IBM cloud, to make our application publicly available we will have to deploy it to a Kubernetes Cluster on IBM cloud, which is a separate step.
